@startuml 0

!define EMPTY_LINE <&transparent>

hide circle
skinparam classAttributeIconSize 0
skinparam titleFontSize 30

skinparam class {
    BackgroundColor<<view>> SkyBlue
    BackgroundColor<<control>> Orange
    BackgroundColor<<model>> LightGreen
    BackgroundColor<<enumeration>> HotPink
    BorderColor Black
}
@enduml